# Generated by Django 3.2.1 on 2021-05-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210510_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='title',
            new_name='content',
        ),
    ]
